---
title: "fs_weather_processing"
author: Natalie Novoseltseva
format: html
---

Measuring Climate Change Effects through Water Quality

Field Station Weather Data EDA

```{r, echo = FALSE, message=FALSE, warning=FALSE}
#libraries
library(tidyverse)
library(dplyr)
library(lubridate)
library(gt)
library(ggplot2)
library(stringr)
```

## Data

```{r}
#field station meteorological data 2001-2026

#creates a data folder
dir.create("Spring2026/data/field_station_weather", recursive = TRUE, showWarnings = FALSE) 

#using tempfile() to create a tempoarry storage
zip <- tempfile(fileext = ".zip")

#downlod the file from the url
download.file("http://cdmo.baruch.sc.edu/aqs/output/854334.zip", zip, mode = "wb")

unzip(zip, exdir = "Spring2026/data/field_station_weather")

#read in the files for all the years as a one data file hudfsmet-p
files <- list.files(
  "data/field_station_weather",
  pattern = "^hudfsmet[0-9]{4}\\.csv$", # ^ -starts a string
                                       # hudfsmet - the exact name in the file (constant)
                                       # any digits from 0-9 might follow
                                       # {4} - we are looking for 4 digits pattern
                                       # \\. - there should be a dot
                                       # csv - it should end with "csv"
                                       # end a string
  full.names = TRUE
)

fs_weather_01_26_raw <- do.call(
  rbind,
  lapply(files, function(f) {
    df <- read.csv(f, fileEncoding = "Latin1")
    df$year <- as.integer(gsub(".*([0-9]{4})\\.csv$", "\\1", f))
    df
  })
)
```

## Data Cleaning

```{r, echo=FALSE, warning=FALSE, message=FALSE}

# Removing empty columns and other irrelant columns
fs_weather_01_26 <- fs_weather_01_26_raw |>
  remove_empty("cols")|>
  select(-StationCode,
        -isSWMP, #historical and provisional Plus columns indicate the status of QAQC
        -Historical, 
        -ProvisionalPlus,
  )

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

#creating a vector with all the flags
flags_weather <- c(
  "F_Record",
  "F_ATemp",
  "F_RH",
  "F_BP",
  "F_WSpd",
  "F_MaxWSpd",
  "F_Wdir",
  "F_SDWDir",
  "F_TotPAR",
  "F_TotPrcp",
  "F_TotSoRad")

flagged_data <- "<-3>|<-2>|<1>"

fs_weather_01_26 <- fs_weather_01_26 |>
  mutate(ATemp = if_else(str_detect(F_ATemp, flagged_data), NA_real_, ATemp),
         RH = if_else(str_detect(F_RH, flagged_data), NA_real_, RH),
         BP = if_else(str_detect(F_BP, flagged_data), NA_real_, BP),
         WSpd = if_else(str_detect(F_WSpd, flagged_data), NA_real_, WSpd),
         MaxWSpd = if_else(str_detect(F_MaxWSpd, flagged_data), NA_real_, MaxWSpd),
         Wdir = if_else(str_detect(F_Wdir, flagged_data), NA_real_, Wdir),
         SDWDir = if_else(str_detect(F_SDWDir, flagged_data), NA_real_, SDWDir),
         TotPAR = if_else(str_detect(F_TotPAR, flagged_data), NA_real_, TotPAR),
         TotPrcp = if_else(str_detect(F_TotPrcp, flagged_data), NA_real_, TotPrcp)
  )

#removing flag columns 
fs_weather_01_26 <- fs_weather_01_26 |> 
  select(-all_of(flags_weather))

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}

#separate the data and time column
fs_weather_01_26 <- fs_weather_01_26 %>%
  mutate(
    DatetimeStamp = as.POSIXct(DatetimeStamp, format = "%m/%d/%Y %H:%M"), #converts the variable into standard POSIXct format
    date = as.Date(DatetimeStamp),
    time = format(DatetimeStamp, "%H:%M:%S")
  )

#create a month column
fs_weather_01_26 <- fs_weather_01_26 %>%
  mutate(
    month = month(DatetimeStamp)          
  )

#create a season column
fs_weather_01_26 <- fs_weather_01_26 %>%
  mutate(
    season = case_when(
      month %in% c(12, 1, 2) ~ "Winter",
      month %in% 3:5        ~ "Spring",
      month %in% 6:8        ~ "Summer",
      month %in% 9:11       ~ "Fall"
    )
  )
```

```{r}
#the code to write out the dataset
write_csv(fs_weather_01_26, "Spring2026/data/fs_weather_01_26.csv")

#uncomment the code to write out the new/updated version of the dataset. It might be better to delete the old one first.
```

